### ISSUE TITLE
Is it possible to play an animation between two specific points in time?

### ISSUE THREAD

**Issue by SaeedMasoumi** [2d-inc/Flare-Flutter#166]
Assume that my animation has a duration about 2 seconds. I want my animation to start from 0.5 to 1.5 and then stop.

**Comment by neurowave** [comment]
You can set this up in Flare using the Work Area, see https://docs.2dimensions.com/support/flare/interface/timeline

Or are you trying to modify this dynamically at runtime?

**Comment by SaeedMasoumi** [comment]
@neurowave I don't mean to modify that. I mean for example if I have `idle` animation and its timeline takes 2 seconds to finish, Is it possible to control the timeline? instead of playing the `idle` animation from 0 to 2, I want to play it dynamically in my flutter app, e.g. from 1 to 2 or 0 to and etc.

**Comment by umberto-sonnino** [comment]
Animations can be controlled programmatically by extending [`FlareControls`](https://github.com/2d-inc/Flare-Flutter/blob/e550a5e55a95209a3cbfba70336bcb2dba17c1d2/flare_flutter/lib/flare_controls.dart), and in particular, the [`advance()`](https://github.com/2d-inc/Flare-Flutter/blob/e550a5e55a95209a3cbfba70336bcb2dba17c1d2/flare_flutter/lib/flare_controls.dart#L56) function. 

You can take a look at how we extended FlareControls [here](https://github.com/2d-inc/Flare-Flutter/blob/e550a5e55a95209a3cbfba70336bcb2dba17c1d2/example/teddy/lib/teddy_controller.dart) for our Teddy Bear example.

**Comment by luigi-rosso** [comment]
To expand on what @umberto-sonnino is saying, you can extend FlareController (or the higher level class FlareControls if you need specific playback functionality it provides) to dynamically apply animations at variable time values (and even apply multiple animations at once). 

In Flare the hierarchy is static, describing the position and dependencies between items. Animations provide changing values that can be applied to that hierarchy to make things move. You can apply multiple animations at different times to affect different parts of the hierarchy concurrently.

Use the [initialize](https://github.com/2d-inc/Flare-Flutter/blob/e550a5e55a95209a3cbfba70336bcb2dba17c1d2/flare_flutter/lib/flare_controller.dart#L30) method to find parts of the hierarchy (or animations) that you are interested in using:
```dart
void initialize(FlutterActorArtboard artboard) {
  this.idle = artboard.getAnimation("idle");
}
```

Then you can use advance to [apply](https://github.com/2d-inc/Flare-Flutter/blob/e550a5e55a95209a3cbfba70336bcb2dba17c1d2/flare_flutter/lib/flare_controller.dart#L37) it to the hierarchy at whatever time value you'd like. FlareControls accumulates this so that it effectively acts like the animation is playing back in realtime, but you could drive the animation via a sin wave, or whatever other function/logic you desire, even random values:
```dart
bool advance(FlutterActorArtboard artboard, double elapsed) {
  this.idle.apply(artboard, new Random().nextDouble(), 1.0);
  return true;
}
```

**Comment by SaeedMasoumi** [comment]
Thank you very much, guys.
