### ISSUE TITLE
Flutter3 Error

### ISSUE THREAD

**Issue by Junesui** [2d-inc/Flare-Flutter#323]
flare_flutter-3.0.2/lib/flare_render_box.dart:167:26: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.

**Comment by tsinis** [comment]
Hey @Junesui, seems like this package is not maintained anymore, you will probably have to move to Rive 2 soon. Otherwise, you can use it [like that](https://github.com/2d-inc/Flare-Flutter/issues/319#issuecomment-1150780023). Basically provide dependency from the [update PR](https://github.com/2d-inc/Flare-Flutter/pull/320).

**Comment by j3g** [comment]
agreed. but the issue some of us are having is other projects like cool_alert depend on this project. so it is not all that straight forward to fix. thank you for sharing a link to a fork that has fixed this. I added it to my 
`dependency_overrides:
  flare_flutter:
      git:
        url: https://github.com/tsinis/Flare-Flutter
        path: flare_flutter/
`
