### ISSUE TITLE
teddy looking direction

### ISSUE THREAD

**Issue by barzansaeedpour** [2d-inc/Flare-Flutter#82]
teddy's looking direction isn't changing during typing. i'm using flutter 1.2.1 stable and flutter_flare 1.5.0 .
i haven't changed anything.

**Comment by luigi-rosso** [comment]
Thanks for reporting this @barzansaeedpour, which teddy example are you using? If it's from this repository, which branch is it?

**Comment by jaggernod** [comment]
Hey @luigi-rosso, I have also noticed that on a bigger screen (tablet or desktop). 

In this screenshot, Teddy is looking to the right despite the caret being on the left:

![Screenshot from 2019-05-19 11 44 17](https://user-images.githubusercontent.com/2519463/57980409-a7dd6e80-7a2b-11e9-8f18-03a4b1af7cd8.png)

For me, this happens when the *Flare World* is not the same as the "Flutter Word".
For example, the Flare Agent does not occupy the whole screen.
The thing that I noticed that the `_caretGlobal` is not properly transformed into `_caretWorld`. It always stays the same.
This is because the `_globalToFlareWorld` is always the default one as the `setViewTransform` is never called. 

Noticed that the call to `setViewTransform` has been removed from Flare's framework sometime after v1.3.

**Comment by luigi-rosso** [comment]
Good catch, we did accidentally remove setViewTransform! I'm looking into this.

**Comment by luigi-rosso** [comment]
This should now be fixed on all channels (master, dev, stable).

**Comment by luigi-rosso** [comment]
Closing this issue, feel free to re-open if you run into further problems with it.
